# Generated by Django 5.1 on 2024-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indumentaria', '0002_botin_image_camiseta_image_short_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='botin',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='botin',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
